[package]
name = "chapterlm"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = "0.8.4"
candle-nn = "0.8.4"
serde = "1.0.219"
serde_json = "1.0.140"
tokenizers = "0.21.1"
tracing = "0.1.41"
